---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "RHQ"
keywords:    "RHQ, monitoring, management, open-source, Red Hat"
description: "Project landing page of RHQ. RHQ is an enterprise management solution for JBoss middleware projects, Tomcat, Apache Web Server, and numerous other server-side applications."
source_link: "https://github.com/rhq-project/rhq"
favicon:     "img/favicon.png"
touch_icon:  "img/rhq-touch-icon.png"
google_analytics_key: UA-10656779-1


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#2592C0'
  red:       '#C03936'
  purple:    '#18bc9c'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  rhqBlue:   '#314b6a'
